$(document).ready(function(){

var substringMatcher = function(strs) {
  return function findMatches(q, cb) {
    var matches, substringRegex;

    // an array that will be populated with substring matches
    matches = [];

    // regex used to determine if a string contains the substring `q`
    substrRegex = new RegExp(q, 'i');

    // iterate through the pool of strings and for any string that
    // contains the substring `q`, add it to the `matches` array
    $.each(strs, function(i, str) {
      if (substrRegex.test(str)) {
        matches.push(str);
      }
    });

    cb(matches);
  };
};

var states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
  'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii',
  'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
  'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
  'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
  'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
  'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
  'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
  'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
];

var ships = [
"Abaddon",					
"Absolution",		
"Aeon",				 	
"Algos",					
"Anathema",				 	
"Anshar",			 	
"Apocalypse",					
"Apocalypse Navy Issue",	 				
"Apocalypse Imperial Issue",	 				
"Apotheosis",	 			
"Arazu",				  	
"Arbitrator",				 	
"Archon",					
"Ares",		
"Ark",				 	
"Armageddon",					
"Ashimmu",	 			
"Astarte",					
"Astero",	 			
"Atron",				
"Augoror",				
"Augoror Navy Issue",	 			
"Avatar",			 	
"Badger",				
"Bantam",					
"Basilisk",	
"Bellicose",				
"Bestower",				
"Bhaalgorn",	 			
"Blackbird",				
"Breacher",					
"Broadsword",				 	
"Brutix",		
"Burst",				
"Bustard",				
"Buzzard",				 	
"Caldari Navy Hookbill",	 				
"Caracal",				
"Catalyst",				
"Celestis",					
"Cerberus",	 				
"Chameleon",				
"Cheetah",				 	
"Chimera",				
"Claw",		
"Claymore",				 
"Coercer",					
"Condor",					
"Confessor",				
"Corax",					
"Cormorant",					
"Covetor",		
"Crane",					
"Crow",		
"Crucifier",					
"Cruor",	 				
"Crusader",					
"Curse",					
"Cyclone",					
"Cynabal",	 				
"Damnation",					
"Daredevil",	 				
"Deimos",	 				
"Devoter",				 	
"Dominix",					
"Dragoon",					
"Drake",		
"Dramiel",	 				
"Eagle",	 				
"Enyo",	 				
"Eos",					
"Erebus",			 	
"Eris",					
"Executioner",					
"Exequror",					
"Exequror Navy Issue",	 			
"Falcon",				
"Ferox",					
"Flycatcher",					
"Federation Navy Comet",	 				
"Garmur",	 			
"Gila",	 				
"Gnosis",	 		
"Gold Magnate",	 				
"Golem",					
"Goru/'s Shuttle",	 				
"Griffin",				
"Guardian",		
"Guardian-Vexor",	 				
"Guristas Shuttle",	 			
"Harbinger",				
"Harpy",	 				
"Hawk",	 				
"Hecate",	 				
"Hel",				 	
"Helios",				 	
"Heretic",					
"Heron",					
"Hoarder",				
"Hound",					
"Huginn",					
"Hulk",		
"Hurricane",					
"Hyena",		
"Hyperion",					
"Ibis",					
"Imicus",					
"Impairor",					
"Impel",					
"Imperial Navy Slicer",	 				
"Incursus",					
"Inquisitor",					
"Ishkur",	 				
"Ishtar",	 				
"Iteron Mark V",				
"Jaguar",	 				
"Jackdaw",	 				
"Keres",	 				
"Kestrel",					
"Kitsune",	
"Kronos",				
"Lachesis",				  	
"Legion",	 				
"Leviathan",				 	
"Loki",	 				
"Machariel",	 				
"Mackinaw",				
"Maelstrom",					
"Magnate",					
"Malediction",				 
"Maller",				
"Mammoth",				
"Manticore",					
"Mastodon",					
"Maulus",					
"Megathron",					
"Megathron Federate Issue",	 				
"Megathron Navy Issue",	 				
"Merlin",					
"Moa",					
"Moros",					
"Muninn",	 				
"Myrmidon",					
"Naga",					
"Naglfar",					
"Navitas",					
"Nemesis",					
"Nereus",				 	
"Nidhoggur",				 
"Nighthawk",					
"Nightmare",	 				
"Nomad",				 	
"Nyx",				 	
"Occator",					
"Omen",					
"Omen Navy Issue",	 				
"Oneiros",	 				
"Onyx",				 	
"Oracle",					
"Orca",	 		  
"Osprey",				 	
"Osprey Navy Issue",	 				
"Paladin",					
"Panther",					
"Phantasm",	 				
"Phobos",				 	
"Phoenix",					
"Pilgrim",				
"Prorator",				
"Probe",					
"Procurer",				
"Prophecy",					
"Prospect",		  
"Proteus",	 				
"Prowler",				
"Punisher",					
"Purifier",					
"Ragnarok",				 	
"Rapier",				 	
"Raptor",					
"Rattlesnake",	 				
"Raven",					
"Raven Navy Issue",	 				
"Raven State Issue",	 				
"Reaper",				
"Redeemer",				 	
"Republic Fleet Firetail",	 				
"Retribution",	 				
"Retriever",				
"Revelation",					
"Rhea",				 	
"Rifter",					
"Rokh",					
"Rook",					
"Rorqual",			 	
"Rupture",					
"Sabre",					
"Sacrilege",	 				
"Scimitar",	 			 	
"Scorpion",					
"Scythe",				 	
"Scythe Fleet Issue",	 				
"Sentinel",	 				
"Sigil",				
"Silver Magnate",	 				
"Sin",				 	
"Skiff",				
"Slasher",					
"Sleipnir",					
"Stabber",					
"Stabber Fleet Issue",	 				
"Stiletto",				 	
"Stratios",	 				
"Succubus",	 				
"Svipul",	 				
"Talos",					
"Talwar",					
"Taranis",					
"Tempest",					
"Tempest Fleet Issue",	 				
"Tempest Tribal Issue",	 				
"Tengu",	 				
"Thanatos",				 
"Thorax",				 	
"Thrasher",					
"Tormentor",					
"Tornado",					
"Tristan",					
"Typhoon",					
"Vagabond",	 				
"Vargur",					
"Velator",				
"Vengeance",	 				
"Vexor",					
"Vexor Navy Issue",	 				
"Viator",				 	
"Vigil",					
"Vigilant",	 				
"Vindicator",	 				
"Vulture",					
"Widow",					
"Wolf",	 				
"Worm",	 				
"Wreathe",				 	
"Wyvern",				 	
"Zealot",	 				
];

$('#the-basics .typeahead').typeahead({
  hint: true,
  highlight: true,
  minLength: 1
},
{
  name: 'ships',
  source: substringMatcher(ships)
});

});




